### PR TITLE
Added all the stuff needed to resolve issue #8

### PR DESCRIPTION
**Pull request by zapodot**
The pom should now be compatible with the requirements specified in http://central.sonatype.org/pages/apache-maven.html 

In order to deploy your release you need:
* an account at Sonatype's Nexus (see http://central.sonatype.org/pages/ossrh-guide.html#review-requirements )
* you must add your Sonatype Nexus credentials to your settings.xml under with "ossrh"
* GPG installed on your build computer AND a GPG key to sign your deployables with

With all those things in place: just run mvn -P release clean deploy

### CODE REVIEW

**Comment by kennycason** [comment]
Nice! I'm very excited. I will shoot to get it deployed this weekend! Thanks for the first PR!

**Comment by kennycason** [comment]
@zapodot I think I have it released. Not 100% sure if I did everything correct. It also doesn't show up in maven central yet. Though I heard it can take some time for it to propagate through to search.
https://oss.sonatype.org/content/repositories/releases/com/kennycason/kumo/1.0/

**Comment by kennycason** [comment]
```xml
        <dependency>
            <groupId>com.kennycason</groupId>
            <artifactId>kumo</artifactId>
            <version>1.0</version>
        </dependency>
```
seemed to work!

**Comment by zapodot** [comment]
Nice!

Congrats @kennycason :-)

**Pull request merged**
